// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsVenueBooking.Data;

#nullable disable

namespace SportsVenueBooking.Migrations
{
    [DbContext(typeof(SportsVenueBookingContext))]
    [Migration("20250208042535_AddBidding")]
    partial class AddBidding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SportsVenueBooking.Data.SportsVenueBookingUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b81513e5-8416-4a1e-a152-5ac2eab982cd",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECWiI+JsU7gETS4ZO3Alix+3lDbW9W38s0aacSS4zx+RkxGR3MADK6bRtanxdoheRA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2ff655a3-2c8c-43a7-b8a0-a2bbf0cfc691",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Bidding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddHours")
                        .HasColumnType("int");

                    b.Property<int>("AddMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("AppointtedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("BidAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("BidDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BidEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BidStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("SportLocationTimeSlotId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SportLocationTimeSlotId");

                    b.ToTable("Bidding");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Bookings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancellationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SportLocationTimeslot1Id")
                        .HasColumnType("int");

                    b.Property<int?>("SportLocationTimeslot2Id")
                        .HasColumnType("int");

                    b.Property<int?>("SportLocationTimeslotId1")
                        .HasColumnType("int");

                    b.Property<int?>("SportLocationTimeslotId2")
                        .HasColumnType("int");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SportLocationTimeslot1Id");

                    b.HasIndex("SportLocationTimeslot2Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.ContactUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsElderlyDiscount")
                        .HasColumnType("bit");

                    b.Property<int>("MaxUses")
                        .HasColumnType("int");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "5 Bishan St 14, Singapore 579783",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(3996),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4014),
                            Name = "Bishan Sports Hall",
                            UpdatedBy = "System",
                            capacity = 5000
                        },
                        new
                        {
                            Id = 2,
                            Address = "57 Anchorvale Rd, Singapore 544964",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4018),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4019),
                            Name = "Sengkang Sports Hall",
                            UpdatedBy = "System",
                            capacity = 2000
                        },
                        new
                        {
                            Id = 3,
                            Address = "21 Jurong East St 31, Singapore 609517",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4022),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4023),
                            Name = "Jurong East Sports Hall",
                            UpdatedBy = "System",
                            capacity = 4000
                        },
                        new
                        {
                            Id = 4,
                            Address = "1 Tampines Walk, Singapore 528523",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4026),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4027),
                            Name = "Tampines Sports Hall",
                            UpdatedBy = "System",
                            capacity = 3500
                        },
                        new
                        {
                            Id = 5,
                            Address = "3 Woodlands St 13, Singapore 738600",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4030),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4031),
                            Name = "Woodlands Sports Hall",
                            UpdatedBy = "System",
                            capacity = 2500
                        },
                        new
                        {
                            Id = 6,
                            Address = "120 Pasir Ris Central, Singapore 519640",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4034),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4035),
                            Name = "Pasir Ris Sports Hall",
                            UpdatedBy = "System",
                            capacity = 2200
                        },
                        new
                        {
                            Id = 7,
                            Address = "1 Yishun Ave 3, Singapore 768101",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4039),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4040),
                            Name = "Yishun Sports Hall",
                            UpdatedBy = "System",
                            capacity = 2700
                        },
                        new
                        {
                            Id = 8,
                            Address = "2 Bukit Batok St 21, Singapore 659604",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4043),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4044),
                            Name = "Bukit Gombak Sports Hall",
                            UpdatedBy = "System",
                            capacity = 3000
                        },
                        new
                        {
                            Id = 9,
                            Address = "473 Stirling Rd, Singapore 148947",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4047),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4048),
                            Name = "Queenstown Sports Centre",
                            UpdatedBy = "System",
                            capacity = 1500
                        },
                        new
                        {
                            Id = 10,
                            Address = "30 Bedok North Dr, Singapore 469658",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4051),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4052),
                            Name = "Bedok Sports Centre",
                            UpdatedBy = "System",
                            capacity = 2200
                        },
                        new
                        {
                            Id = 11,
                            Address = "21 Canberra Link, Singapore 768137",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4055),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4056),
                            Name = "Bukit Canberra Sports Centre",
                            UpdatedBy = "System",
                            capacity = 4000
                        },
                        new
                        {
                            Id = 12,
                            Address = "60 Simei St 1, Singapore 529944",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4059),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4060),
                            Name = "Changi Simei Sports Hall",
                            UpdatedBy = "System",
                            capacity = 1800
                        },
                        new
                        {
                            Id = 13,
                            Address = "23 Serangoon North Ave 1, Singapore 555881",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4063),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4064),
                            Name = "Serangoon Sports Centre",
                            UpdatedBy = "System",
                            capacity = 2800
                        },
                        new
                        {
                            Id = 14,
                            Address = "900 Tiong Bahru Rd, Singapore 158790",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4067),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4068),
                            Name = "Delta Sports Centre",
                            UpdatedBy = "System",
                            capacity = 3500
                        },
                        new
                        {
                            Id = 15,
                            Address = "21 Choa Chu Kang Ave 4, Singapore 689812",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4071),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4072),
                            Name = "Choa Chu Kang Sports Centre",
                            UpdatedBy = "System",
                            capacity = 2500
                        },
                        new
                        {
                            Id = 16,
                            Address = "15 Francis Thomas Dr, Singapore 359342",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4075),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4076),
                            Name = "St. Andrew's Secondary School Sports Hall",
                            UpdatedBy = "System",
                            capacity = 800
                        },
                        new
                        {
                            Id = 17,
                            Address = "1 Raffles Institution Lane, Singapore 575954",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4079),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4080),
                            Name = "Raffles Institution Sports Hall",
                            UpdatedBy = "System",
                            capacity = 600
                        },
                        new
                        {
                            Id = 18,
                            Address = "25 Winstedt Rd, Singapore 227977",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4083),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4084),
                            Name = "Anglo-Chinese School Sports Hall",
                            UpdatedBy = "System",
                            capacity = 900
                        },
                        new
                        {
                            Id = 19,
                            Address = "40 Nanyang Walk, Singapore 639798",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4087),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4088),
                            Name = "Nanyang Primary School Hall",
                            UpdatedBy = "System",
                            capacity = 500
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOnCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSlots")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SportLocationTimeslotId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SportLocationTimeslotId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSlots = 20,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5621),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5622),
                            ScheduledDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SportLocationTimeslotId = 1,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            AvailableSlots = 15,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5630),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5631),
                            ScheduledDate = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SportLocationTimeslotId = 2,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            AvailableSlots = 25,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5635),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5636),
                            ScheduledDate = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SportLocationTimeslotId = 3,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            AvailableSlots = 10,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5639),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5640),
                            ScheduledDate = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SportLocationTimeslotId = 4,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            AvailableSlots = 20,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5643),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5644),
                            ScheduledDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SportLocationTimeslotId = 6,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4651),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4653),
                            ImagePath = "images/badminton.png",
                            Name = "Badminton",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4656),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4657),
                            ImagePath = "images/basketball.png",
                            Name = "Basketball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4660),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4661),
                            ImagePath = "images/beach_volleyball.png",
                            Name = "Beach Volleyball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4664),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4665),
                            ImagePath = "images/volleyball.png",
                            Name = "Volleyball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4668),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4669),
                            ImagePath = "images/dance.png",
                            Name = "Dance",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4672),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4673),
                            ImagePath = "images/floorball logo.jpg",
                            Name = "Floorball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4676),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4677),
                            ImagePath = "images/frisbee logo.png",
                            Name = "Frisbee",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4680),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4681),
                            ImagePath = "images/handball.jpg",
                            Name = "Handball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4684),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4685),
                            ImagePath = "images/lawnbowl.png",
                            Name = "Lawn Bowl",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4788),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4790),
                            ImagePath = "images/netball.jpg",
                            Name = "Netball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4793),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4794),
                            ImagePath = "images/petanque.jpg",
                            Name = "Petanque",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4796),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4798),
                            ImagePath = "images/pickleball.jpg",
                            Name = "Pickleball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4800),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4801),
                            ImagePath = "images/sepak.png",
                            Name = "Sepak",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4804),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4805),
                            ImagePath = "images/squash.png",
                            Name = "Squash",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4808),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4809),
                            ImagePath = "images/table_tennis.png",
                            Name = "Table Tennis",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4812),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4813),
                            ImagePath = "images/soccer.png",
                            Name = "Soccer",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4816),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4817),
                            ImagePath = "images/hockey.png",
                            Name = "Hockey",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4820),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(4821),
                            ImagePath = "images/tennis.png",
                            Name = "Tennis",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.SportLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("SportId");

                    b.ToTable("SportLocation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5066),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5067),
                            LocationId = 2,
                            SportId = 1,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5070),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5071),
                            LocationId = 1,
                            SportId = 1,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5074),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5075),
                            LocationId = 2,
                            SportId = 2,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5077),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5078),
                            LocationId = 14,
                            SportId = 2,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5081),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5082),
                            LocationId = 1,
                            SportId = 3,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5085),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5086),
                            LocationId = 17,
                            SportId = 3,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5089),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5090),
                            LocationId = 2,
                            SportId = 4,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5093),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5094),
                            LocationId = 15,
                            SportId = 4,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5096),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5097),
                            LocationId = 1,
                            SportId = 5,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5100),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5101),
                            LocationId = 16,
                            SportId = 5,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5104),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5105),
                            LocationId = 3,
                            SportId = 6,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5108),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5109),
                            LocationId = 18,
                            SportId = 6,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5112),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5113),
                            LocationId = 4,
                            SportId = 7,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5116),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5117),
                            LocationId = 5,
                            SportId = 8,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5120),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5121),
                            LocationId = 6,
                            SportId = 9,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5124),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5125),
                            LocationId = 19,
                            SportId = 9,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5128),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5129),
                            LocationId = 7,
                            SportId = 10,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5131),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5132),
                            LocationId = 8,
                            SportId = 11,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5135),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5136),
                            LocationId = 9,
                            SportId = 12,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5139),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5140),
                            LocationId = 2,
                            SportId = 12,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5143),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5144),
                            LocationId = 10,
                            SportId = 13,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5147),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5148),
                            LocationId = 11,
                            SportId = 14,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5151),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5152),
                            LocationId = 12,
                            SportId = 15,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5154),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5155),
                            LocationId = 13,
                            SportId = 16,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 25,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5158),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5159),
                            LocationId = 14,
                            SportId = 17,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.SportLocationTimeslot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SportLocationId")
                        .HasColumnType("int");

                    b.Property<int>("TimeslotId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SportLocationId");

                    b.HasIndex("TimeslotId");

                    b.ToTable("SportLocationTimeslots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50.0,
                            SportLocationId = 1,
                            TimeslotId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 45.0,
                            SportLocationId = 1,
                            TimeslotId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 55.0,
                            SportLocationId = 2,
                            TimeslotId = 2
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 60.0,
                            SportLocationId = 3,
                            TimeslotId = 3
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 65.0,
                            SportLocationId = 4,
                            TimeslotId = 4
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50.0,
                            SportLocationId = 1,
                            TimeslotId = 3
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Timeslot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Timeslot");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5400),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5401),
                            Description = "08:00 AM - 09:00 AM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5403),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5404),
                            Description = "09:00 AM - 10:00 AM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5407),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5408),
                            Description = "10:00 AM - 11:00 AM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5410),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5411),
                            Description = "11:00 AM - 12:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5414),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5415),
                            Description = "12:00 PM - 01:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5418),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5419),
                            Description = "01:00 PM - 02:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5421),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5422),
                            Description = "02:00 PM - 03:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5425),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5426),
                            Description = "03:00 PM - 04:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5429),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5430),
                            Description = "04:00 PM - 05:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5432),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5433),
                            Description = "05:00 PM - 06:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5436),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5437),
                            Description = "06:00 PM - 07:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5440),
                            DateUpdated = new DateTime(2025, 2, 8, 12, 25, 31, 954, DateTimeKind.Local).AddTicks(5441),
                            Description = "07:00 PM - 08:00 PM",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SportsVenueBooking.Data.SportsVenueBookingUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SportsVenueBooking.Data.SportsVenueBookingUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsVenueBooking.Data.SportsVenueBookingUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SportsVenueBooking.Data.SportsVenueBookingUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Bidding", b =>
                {
                    b.HasOne("SportsVenueBooking.Domain.SportLocationTimeslot", "SportLocationTimeslots")
                        .WithMany()
                        .HasForeignKey("SportLocationTimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportLocationTimeslots");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Bookings", b =>
                {
                    b.HasOne("SportsVenueBooking.Domain.SportLocationTimeslot", "SportLocationTimeslot1")
                        .WithMany()
                        .HasForeignKey("SportLocationTimeslot1Id");

                    b.HasOne("SportsVenueBooking.Domain.SportLocationTimeslot", "SportLocationTimeslot2")
                        .WithMany()
                        .HasForeignKey("SportLocationTimeslot2Id");

                    b.Navigation("SportLocationTimeslot1");

                    b.Navigation("SportLocationTimeslot2");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Payment", b =>
                {
                    b.HasOne("SportsVenueBooking.Domain.Bookings", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Schedule", b =>
                {
                    b.HasOne("SportsVenueBooking.Domain.SportLocationTimeslot", "SportLocationTimeslot")
                        .WithMany()
                        .HasForeignKey("SportLocationTimeslotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportLocationTimeslot");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.SportLocation", b =>
                {
                    b.HasOne("SportsVenueBooking.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsVenueBooking.Domain.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.SportLocationTimeslot", b =>
                {
                    b.HasOne("SportsVenueBooking.Domain.SportLocation", "SportLocation")
                        .WithMany()
                        .HasForeignKey("SportLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsVenueBooking.Domain.Timeslot", "Timeslot")
                        .WithMany()
                        .HasForeignKey("TimeslotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportLocation");

                    b.Navigation("Timeslot");
                });
#pragma warning restore 612, 618
        }
    }
}
