// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsVenueBooking.Data;

#nullable disable

namespace SportsVenueBooking.Migrations
{
    [DbContext(typeof(SportsVenueBookingContext))]
    [Migration("20250119074628_UpdateSeed")]
    partial class UpdateSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SportsVenueBooking.Data.SportsVenueBookingUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "142c5617-4f61-4153-8f58-9d2676e88181",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIjsmT5QSVANP/fowWWcL5nNEoH51WlaB0RsuISk+F+XgfPCV5IhOoa3ofkb5qRFMQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e69ef4ca-6f2a-456c-aad8-ab89ae0a77ce",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Bookings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "5 Bishan St 14, Singapore 579783",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6906),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6919),
                            Name = "Bishan Sports Hall",
                            UpdatedBy = "System",
                            capacity = 5000
                        },
                        new
                        {
                            Id = 2,
                            Address = "57 Anchorvale Rd, Singapore 544964",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6923),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6923),
                            Name = "Sengkang Sports Hall",
                            UpdatedBy = "System",
                            capacity = 2000
                        },
                        new
                        {
                            Id = 3,
                            Address = "21 Jurong East St 31, Singapore 609517",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6926),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6927),
                            Name = "Jurong East Sports Hall",
                            UpdatedBy = "System",
                            capacity = 4000
                        },
                        new
                        {
                            Id = 4,
                            Address = "1 Tampines Walk, Singapore 528523",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6929),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6930),
                            Name = "Tampines Sports Hall",
                            UpdatedBy = "System",
                            capacity = 3500
                        },
                        new
                        {
                            Id = 5,
                            Address = "3 Woodlands St 13, Singapore 738600",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6932),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6933),
                            Name = "Woodlands Sports Hall",
                            UpdatedBy = "System",
                            capacity = 2500
                        },
                        new
                        {
                            Id = 6,
                            Address = "120 Pasir Ris Central, Singapore 519640",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6936),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6936),
                            Name = "Pasir Ris Sports Hall",
                            UpdatedBy = "System",
                            capacity = 2200
                        },
                        new
                        {
                            Id = 7,
                            Address = "1 Yishun Ave 3, Singapore 768101",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6939),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6940),
                            Name = "Yishun Sports Hall",
                            UpdatedBy = "System",
                            capacity = 2700
                        },
                        new
                        {
                            Id = 8,
                            Address = "2 Bukit Batok St 21, Singapore 659604",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6942),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6944),
                            Name = "Bukit Gombak Sports Hall",
                            UpdatedBy = "System",
                            capacity = 3000
                        },
                        new
                        {
                            Id = 9,
                            Address = "473 Stirling Rd, Singapore 148947",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6946),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6947),
                            Name = "Queenstown Sports Centre",
                            UpdatedBy = "System",
                            capacity = 1500
                        },
                        new
                        {
                            Id = 10,
                            Address = "30 Bedok North Dr, Singapore 469658",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6950),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6950),
                            Name = "Bedok Sports Centre",
                            UpdatedBy = "System",
                            capacity = 2200
                        },
                        new
                        {
                            Id = 11,
                            Address = "21 Canberra Link, Singapore 768137",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6953),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6954),
                            Name = "Bukit Canberra Sports Centre",
                            UpdatedBy = "System",
                            capacity = 4000
                        },
                        new
                        {
                            Id = 12,
                            Address = "60 Simei St 1, Singapore 529944",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6956),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6957),
                            Name = "Changi Simei Sports Hall",
                            UpdatedBy = "System",
                            capacity = 1800
                        },
                        new
                        {
                            Id = 13,
                            Address = "23 Serangoon North Ave 1, Singapore 555881",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6960),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6961),
                            Name = "Serangoon Sports Centre",
                            UpdatedBy = "System",
                            capacity = 2800
                        },
                        new
                        {
                            Id = 14,
                            Address = "900 Tiong Bahru Rd, Singapore 158790",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6963),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6964),
                            Name = "Delta Sports Centre",
                            UpdatedBy = "System",
                            capacity = 3500
                        },
                        new
                        {
                            Id = 15,
                            Address = "21 Choa Chu Kang Ave 4, Singapore 689812",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6966),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6967),
                            Name = "Choa Chu Kang Sports Centre",
                            UpdatedBy = "System",
                            capacity = 2500
                        },
                        new
                        {
                            Id = 16,
                            Address = "15 Francis Thomas Dr, Singapore 359342",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6969),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6970),
                            Name = "St. Andrew's Secondary School Sports Hall",
                            UpdatedBy = "System",
                            capacity = 800
                        },
                        new
                        {
                            Id = 17,
                            Address = "1 Raffles Institution Lane, Singapore 575954",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6973),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6973),
                            Name = "Raffles Institution Sports Hall",
                            UpdatedBy = "System",
                            capacity = 600
                        },
                        new
                        {
                            Id = 18,
                            Address = "25 Winstedt Rd, Singapore 227977",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6976),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6977),
                            Name = "Anglo-Chinese School Sports Hall",
                            UpdatedBy = "System",
                            capacity = 900
                        },
                        new
                        {
                            Id = 19,
                            Address = "40 Nanyang Walk, Singapore 639798",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6979),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(6980),
                            Name = "Nanyang Primary School Hall",
                            UpdatedBy = "System",
                            capacity = 500
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSlots")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<int>("SportLocationId")
                        .HasColumnType("int");

                    b.Property<int>("TimeslotId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SportLocationId");

                    b.HasIndex("TimeslotId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSlots = 20,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(8528),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(8530),
                            Price = 50f,
                            ScheduledDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SportLocationId = 1,
                            TimeslotId = 1,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            AvailableSlots = 15,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(8532),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(8533),
                            Price = 45f,
                            ScheduledDate = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SportLocationId = 2,
                            TimeslotId = 2,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            AvailableSlots = 25,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(8535),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(8536),
                            Price = 55f,
                            ScheduledDate = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SportLocationId = 3,
                            TimeslotId = 1,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            AvailableSlots = 10,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(8538),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(8539),
                            Price = 60f,
                            ScheduledDate = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SportLocationId = 4,
                            TimeslotId = 2,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7391),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7392),
                            ImagePath = "images/badminton.png",
                            Name = "Badminton",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7394),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7395),
                            ImagePath = "images/basketball.png",
                            Name = "Basketball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7397),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7397),
                            ImagePath = "images/beach_volleyball.png",
                            Name = "Beach Volleyball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7399),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7400),
                            ImagePath = "images/volleyball.png",
                            Name = "Volleyball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7402),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7402),
                            ImagePath = "images/dance.png",
                            Name = "Dance",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7404),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7405),
                            ImagePath = "images/floorball logo.jpg",
                            Name = "Floorball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7406),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7407),
                            ImagePath = "images/frisbee logo.png",
                            Name = "Frisbee",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7409),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7409),
                            ImagePath = "images/handball.jpg",
                            Name = "Handball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7411),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7412),
                            ImagePath = "images/lawnbowl.png",
                            Name = "Lawn Bowl",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7413),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7414),
                            ImagePath = "images/netball.jpg",
                            Name = "Netball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7416),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7416),
                            ImagePath = "images/petanque.jpg",
                            Name = "Petanque",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7418),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7419),
                            ImagePath = "images/pickleball.jpg",
                            Name = "Pickleball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7420),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7421),
                            ImagePath = "images/sepak.png",
                            Name = "Sepak",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7515),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7516),
                            ImagePath = "images/squash.png",
                            Name = "Squash",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7518),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7518),
                            ImagePath = "images/table_tennis.png",
                            Name = "Table Tennis",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7520),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7521),
                            ImagePath = "images/soccer.png",
                            Name = "Soccer",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7523),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7523),
                            ImagePath = "images/hockey.png",
                            Name = "Hockey",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7525),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7526),
                            ImagePath = "images/tennis.png",
                            Name = "Tennis",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.SportLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("SportId");

                    b.ToTable("SportLocation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7661),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7662),
                            LocationId = 2,
                            SportId = 1,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7663),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7664),
                            LocationId = 1,
                            SportId = 1,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7666),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7666),
                            LocationId = 2,
                            SportId = 2,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7668),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7669),
                            LocationId = 14,
                            SportId = 2,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7670),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7671),
                            LocationId = 1,
                            SportId = 3,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7672),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7673),
                            LocationId = 17,
                            SportId = 3,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7675),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7675),
                            LocationId = 2,
                            SportId = 4,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7677),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7678),
                            LocationId = 15,
                            SportId = 4,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7679),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7680),
                            LocationId = 1,
                            SportId = 5,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7682),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7682),
                            LocationId = 16,
                            SportId = 5,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7684),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7685),
                            LocationId = 3,
                            SportId = 6,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7686),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7687),
                            LocationId = 18,
                            SportId = 6,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7689),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7689),
                            LocationId = 4,
                            SportId = 7,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7691),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7692),
                            LocationId = 5,
                            SportId = 8,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7693),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7694),
                            LocationId = 6,
                            SportId = 9,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7696),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7696),
                            LocationId = 19,
                            SportId = 9,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7698),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7698),
                            LocationId = 7,
                            SportId = 10,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7700),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7701),
                            LocationId = 8,
                            SportId = 11,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7702),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7703),
                            LocationId = 9,
                            SportId = 12,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7705),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7705),
                            LocationId = 2,
                            SportId = 12,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7707),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7707),
                            LocationId = 10,
                            SportId = 13,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7709),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7710),
                            LocationId = 11,
                            SportId = 14,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7711),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7712),
                            LocationId = 12,
                            SportId = 15,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7713),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7714),
                            LocationId = 13,
                            SportId = 16,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 25,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7716),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7716),
                            LocationId = 14,
                            SportId = 17,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Timeslot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Timeslot");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7859),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7860),
                            Description = "08:00 AM - 09:00 AM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7861),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7862),
                            Description = "09:00 AM - 10:00 AM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7864),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7864),
                            Description = "10:00 AM - 11:00 AM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7866),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7866),
                            Description = "11:00 AM - 12:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7868),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7869),
                            Description = "12:00 PM - 01:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7870),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7871),
                            Description = "01:00 PM - 02:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7873),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7873),
                            Description = "02:00 PM - 03:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7875),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7875),
                            Description = "03:00 PM - 04:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7877),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7878),
                            Description = "04:00 PM - 05:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7879),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7880),
                            Description = "05:00 PM - 06:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7881),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7882),
                            Description = "06:00 PM - 07:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7884),
                            DateUpdated = new DateTime(2025, 1, 19, 15, 46, 27, 541, DateTimeKind.Local).AddTicks(7884),
                            Description = "07:00 PM - 08:00 PM",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SportsVenueBooking.Data.SportsVenueBookingUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SportsVenueBooking.Data.SportsVenueBookingUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsVenueBooking.Data.SportsVenueBookingUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SportsVenueBooking.Data.SportsVenueBookingUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Schedule", b =>
                {
                    b.HasOne("SportsVenueBooking.Domain.SportLocation", "SportLocation")
                        .WithMany()
                        .HasForeignKey("SportLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsVenueBooking.Domain.Timeslot", "Timeslots")
                        .WithMany()
                        .HasForeignKey("TimeslotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportLocation");

                    b.Navigation("Timeslots");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.SportLocation", b =>
                {
                    b.HasOne("SportsVenueBooking.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsVenueBooking.Domain.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Sport");
                });
#pragma warning restore 612, 618
        }
    }
}
