// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsVenueBooking.Data;

#nullable disable

namespace SportsVenueBooking.Migrations
{
    [DbContext(typeof(SportsVenueBookingContext))]
    [Migration("20250122044831_UpdateSeed")]
    partial class UpdateSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("CardBrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastFourDigits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeChargeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeReceiptUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("SportsVenueBooking.Data.SportsVenueBookingUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2cbb1922-5e17-4e97-89d8-0550130047b0",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFCGLHUnE52apw7IZRNk8aPym3xqi7xLQtrj5kIxcP/6Z7CSWisuV3yPpUf4iE40yg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5b4889a2-897c-4664-8ede-a30d37899263",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Bookings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancellationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SportLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("SportLocationTimeslotId")
                        .HasColumnType("int");

                    b.Property<string>("SportName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeslotDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SportLocationId");

                    b.HasIndex("SportLocationTimeslotId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "5 Bishan St 14, Singapore 579783",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8200),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8210),
                            Name = "Bishan Sports Hall",
                            UpdatedBy = "System",
                            capacity = 5000
                        },
                        new
                        {
                            Id = 2,
                            Address = "57 Anchorvale Rd, Singapore 544964",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8213),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8213),
                            Name = "Sengkang Sports Hall",
                            UpdatedBy = "System",
                            capacity = 2000
                        },
                        new
                        {
                            Id = 3,
                            Address = "21 Jurong East St 31, Singapore 609517",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8215),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8216),
                            Name = "Jurong East Sports Hall",
                            UpdatedBy = "System",
                            capacity = 4000
                        },
                        new
                        {
                            Id = 4,
                            Address = "1 Tampines Walk, Singapore 528523",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8218),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8218),
                            Name = "Tampines Sports Hall",
                            UpdatedBy = "System",
                            capacity = 3500
                        },
                        new
                        {
                            Id = 5,
                            Address = "3 Woodlands St 13, Singapore 738600",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8220),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8221),
                            Name = "Woodlands Sports Hall",
                            UpdatedBy = "System",
                            capacity = 2500
                        },
                        new
                        {
                            Id = 6,
                            Address = "120 Pasir Ris Central, Singapore 519640",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8223),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8223),
                            Name = "Pasir Ris Sports Hall",
                            UpdatedBy = "System",
                            capacity = 2200
                        },
                        new
                        {
                            Id = 7,
                            Address = "1 Yishun Ave 3, Singapore 768101",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8225),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8226),
                            Name = "Yishun Sports Hall",
                            UpdatedBy = "System",
                            capacity = 2700
                        },
                        new
                        {
                            Id = 8,
                            Address = "2 Bukit Batok St 21, Singapore 659604",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8228),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8228),
                            Name = "Bukit Gombak Sports Hall",
                            UpdatedBy = "System",
                            capacity = 3000
                        },
                        new
                        {
                            Id = 9,
                            Address = "473 Stirling Rd, Singapore 148947",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8230),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8231),
                            Name = "Queenstown Sports Centre",
                            UpdatedBy = "System",
                            capacity = 1500
                        },
                        new
                        {
                            Id = 10,
                            Address = "30 Bedok North Dr, Singapore 469658",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8233),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8233),
                            Name = "Bedok Sports Centre",
                            UpdatedBy = "System",
                            capacity = 2200
                        },
                        new
                        {
                            Id = 11,
                            Address = "21 Canberra Link, Singapore 768137",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8235),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8236),
                            Name = "Bukit Canberra Sports Centre",
                            UpdatedBy = "System",
                            capacity = 4000
                        },
                        new
                        {
                            Id = 12,
                            Address = "60 Simei St 1, Singapore 529944",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8237),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8238),
                            Name = "Changi Simei Sports Hall",
                            UpdatedBy = "System",
                            capacity = 1800
                        },
                        new
                        {
                            Id = 13,
                            Address = "23 Serangoon North Ave 1, Singapore 555881",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8240),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8240),
                            Name = "Serangoon Sports Centre",
                            UpdatedBy = "System",
                            capacity = 2800
                        },
                        new
                        {
                            Id = 14,
                            Address = "900 Tiong Bahru Rd, Singapore 158790",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8242),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8243),
                            Name = "Delta Sports Centre",
                            UpdatedBy = "System",
                            capacity = 3500
                        },
                        new
                        {
                            Id = 15,
                            Address = "21 Choa Chu Kang Ave 4, Singapore 689812",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8245),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8245),
                            Name = "Choa Chu Kang Sports Centre",
                            UpdatedBy = "System",
                            capacity = 2500
                        },
                        new
                        {
                            Id = 16,
                            Address = "15 Francis Thomas Dr, Singapore 359342",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8247),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8248),
                            Name = "St. Andrew's Secondary School Sports Hall",
                            UpdatedBy = "System",
                            capacity = 800
                        },
                        new
                        {
                            Id = 17,
                            Address = "1 Raffles Institution Lane, Singapore 575954",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8249),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8250),
                            Name = "Raffles Institution Sports Hall",
                            UpdatedBy = "System",
                            capacity = 600
                        },
                        new
                        {
                            Id = 18,
                            Address = "25 Winstedt Rd, Singapore 227977",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8252),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8252),
                            Name = "Anglo-Chinese School Sports Hall",
                            UpdatedBy = "System",
                            capacity = 900
                        },
                        new
                        {
                            Id = 19,
                            Address = "40 Nanyang Walk, Singapore 639798",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8254),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8255),
                            Name = "Nanyang Primary School Hall",
                            UpdatedBy = "System",
                            capacity = 500
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSlots")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SportLocationTimeslotId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("totalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SportLocationTimeslotId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSlots = 20,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9167),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9168),
                            ScheduledDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SportLocationTimeslotId = 1,
                            UpdatedBy = "System",
                            totalPrice = 0.0
                        },
                        new
                        {
                            Id = 2,
                            AvailableSlots = 15,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9174),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9175),
                            ScheduledDate = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SportLocationTimeslotId = 2,
                            UpdatedBy = "System",
                            totalPrice = 0.0
                        },
                        new
                        {
                            Id = 3,
                            AvailableSlots = 25,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9177),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9177),
                            ScheduledDate = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SportLocationTimeslotId = 3,
                            UpdatedBy = "System",
                            totalPrice = 0.0
                        },
                        new
                        {
                            Id = 4,
                            AvailableSlots = 10,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9179),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9180),
                            ScheduledDate = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SportLocationTimeslotId = 4,
                            UpdatedBy = "System",
                            totalPrice = 0.0
                        },
                        new
                        {
                            Id = 5,
                            AvailableSlots = 20,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9182),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9183),
                            ScheduledDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SportLocationTimeslotId = 6,
                            UpdatedBy = "System",
                            totalPrice = 0.0
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sport");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8504),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8505),
                            ImagePath = "images/badminton.png",
                            Name = "Badminton",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8507),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8508),
                            ImagePath = "images/basketball.png",
                            Name = "Basketball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8509),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8510),
                            ImagePath = "images/beach_volleyball.png",
                            Name = "Beach Volleyball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8512),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8512),
                            ImagePath = "images/volleyball.png",
                            Name = "Volleyball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8514),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8515),
                            ImagePath = "images/dance.png",
                            Name = "Dance",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8516),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8517),
                            ImagePath = "images/floorball logo.jpg",
                            Name = "Floorball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8519),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8519),
                            ImagePath = "images/frisbee logo.png",
                            Name = "Frisbee",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8521),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8522),
                            ImagePath = "images/handball.jpg",
                            Name = "Handball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8523),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8524),
                            ImagePath = "images/lawnbowl.png",
                            Name = "Lawn Bowl",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8526),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8526),
                            ImagePath = "images/netball.jpg",
                            Name = "Netball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8528),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8529),
                            ImagePath = "images/petanque.jpg",
                            Name = "Petanque",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8531),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8531),
                            ImagePath = "images/pickleball.jpg",
                            Name = "Pickleball",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8533),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8534),
                            ImagePath = "images/sepak.png",
                            Name = "Sepak",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8535),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8536),
                            ImagePath = "images/squash.png",
                            Name = "Squash",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8538),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8538),
                            ImagePath = "images/table_tennis.png",
                            Name = "Table Tennis",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8540),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8541),
                            ImagePath = "images/soccer.png",
                            Name = "Soccer",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8542),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8543),
                            ImagePath = "images/hockey.png",
                            Name = "Hockey",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8545),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8545),
                            ImagePath = "images/tennis.png",
                            Name = "Tennis",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.SportLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("SportId");

                    b.ToTable("SportLocation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8689),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8690),
                            LocationId = 2,
                            SportId = 1,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8691),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8692),
                            LocationId = 1,
                            SportId = 1,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8694),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8694),
                            LocationId = 2,
                            SportId = 2,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8696),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8697),
                            LocationId = 14,
                            SportId = 2,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8698),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8699),
                            LocationId = 1,
                            SportId = 3,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8701),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8701),
                            LocationId = 17,
                            SportId = 3,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8703),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8704),
                            LocationId = 2,
                            SportId = 4,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8705),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8706),
                            LocationId = 15,
                            SportId = 4,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8708),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8708),
                            LocationId = 1,
                            SportId = 5,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8710),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8711),
                            LocationId = 16,
                            SportId = 5,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8713),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8713),
                            LocationId = 3,
                            SportId = 6,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8715),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8716),
                            LocationId = 18,
                            SportId = 6,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8717),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8718),
                            LocationId = 4,
                            SportId = 7,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8720),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8720),
                            LocationId = 5,
                            SportId = 8,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8722),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8723),
                            LocationId = 6,
                            SportId = 9,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8724),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8725),
                            LocationId = 19,
                            SportId = 9,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8727),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8727),
                            LocationId = 7,
                            SportId = 10,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8729),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8730),
                            LocationId = 8,
                            SportId = 11,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8731),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8732),
                            LocationId = 9,
                            SportId = 12,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8734),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8734),
                            LocationId = 2,
                            SportId = 12,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8736),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8737),
                            LocationId = 10,
                            SportId = 13,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8738),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8739),
                            LocationId = 11,
                            SportId = 14,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8824),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8825),
                            LocationId = 12,
                            SportId = 15,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8827),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8828),
                            LocationId = 13,
                            SportId = 16,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 25,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8829),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8830),
                            LocationId = 14,
                            SportId = 17,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.SportLocationTimeslot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SportLocationId")
                        .HasColumnType("int");

                    b.Property<int>("TimeslotId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SportLocationId");

                    b.HasIndex("TimeslotId");

                    b.ToTable("SportLocationTimeslots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50.0,
                            SportLocationId = 1,
                            TimeslotId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 45.0,
                            SportLocationId = 1,
                            TimeslotId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 55.0,
                            SportLocationId = 2,
                            TimeslotId = 2
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 60.0,
                            SportLocationId = 3,
                            TimeslotId = 3
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 65.0,
                            SportLocationId = 4,
                            TimeslotId = 4
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50.0,
                            SportLocationId = 1,
                            TimeslotId = 3
                        });
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Timeslot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Timeslot");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8981),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8982),
                            Description = "08:00 AM - 09:00 AM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8984),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8984),
                            Description = "09:00 AM - 10:00 AM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8986),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8986),
                            Description = "10:00 AM - 11:00 AM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8988),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8989),
                            Description = "11:00 AM - 12:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8990),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8991),
                            Description = "12:00 PM - 01:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8992),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8993),
                            Description = "01:00 PM - 02:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8995),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8995),
                            Description = "02:00 PM - 03:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8997),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8997),
                            Description = "03:00 PM - 04:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(8999),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9000),
                            Description = "04:00 PM - 05:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9001),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9002),
                            Description = "05:00 PM - 06:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9003),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9004),
                            Description = "06:00 PM - 07:00 PM",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9006),
                            DateUpdated = new DateTime(2025, 1, 22, 12, 48, 30, 308, DateTimeKind.Local).AddTicks(9006),
                            Description = "07:00 PM - 08:00 PM",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SportsVenueBooking.Data.SportsVenueBookingUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SportsVenueBooking.Data.SportsVenueBookingUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsVenueBooking.Data.SportsVenueBookingUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SportsVenueBooking.Data.SportsVenueBookingUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.HasOne("SportsVenueBooking.Domain.Bookings", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Bookings", b =>
                {
                    b.HasOne("SportsVenueBooking.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsVenueBooking.Domain.SportLocation", "SportLocation")
                        .WithMany()
                        .HasForeignKey("SportLocationId");

                    b.HasOne("SportsVenueBooking.Domain.SportLocationTimeslot", "SportLocationTimeslot")
                        .WithMany()
                        .HasForeignKey("SportLocationTimeslotId");

                    b.HasOne("SportsVenueBooking.Data.SportsVenueBookingUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Customer");

                    b.Navigation("SportLocation");

                    b.Navigation("SportLocationTimeslot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Schedule", b =>
                {
                    b.HasOne("SportsVenueBooking.Domain.SportLocationTimeslot", "SportLocationTimeslot")
                        .WithMany()
                        .HasForeignKey("SportLocationTimeslotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportLocationTimeslot");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.SportLocation", b =>
                {
                    b.HasOne("SportsVenueBooking.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsVenueBooking.Domain.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.SportLocationTimeslot", b =>
                {
                    b.HasOne("SportsVenueBooking.Domain.SportLocation", "SportLocation")
                        .WithMany()
                        .HasForeignKey("SportLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsVenueBooking.Domain.Timeslot", "Timeslot")
                        .WithMany()
                        .HasForeignKey("TimeslotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportLocation");

                    b.Navigation("Timeslot");
                });

            modelBuilder.Entity("SportsVenueBooking.Domain.Bookings", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
